### ISSUE TITLE
Server seems to be refusing connections

### ISSUE THREAD

**Issue by kellydarren** [cloudsyjared/MiThings#14]
Hi Jared
Encountered this issue tonight.

00:38:26: error error: org.apache.http.conn.HttpHostConnectException: Connect to lights.cloudsy.com:80 [lights.cloudsy.com/104.236.41.27] failed: Connection refused

**Comment by cloudsyjared** [comment]
Thanks for the heads up. May have to get to this in the am

**Comment by cloudsyjared** [comment]
Can you let me know if this is fixed?

**Comment by kellydarren** [comment]
Hey

Its still not working, but that earlier error seems to have gone.  Nothing seems to be showing up in the  Live Logging (well not that I could see).

I turned on the MiLight Hub log the turned on the lights, the below lines were produced.

a9a61a99-5cb1-4405-ab36-ea914c68f960  21:51:12: debug Received response: groovyx.net.http.HttpResponseDecorator@12fdedb1 on
a9a61a99-5cb1-4405-ab36-ea914c68f960  21:51:12: debug MiLight device: AC:CF:23:53:D3:8E, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FFFFFF, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
a9a61a99-5cb1-4405-ab36-ea914c68f960  21:51:12: debug MiLight device: AC:CF:23:53:D3:8E, built path: rgbw/power/on/3
a9a61a99-5cb1-4405-ab36-ea914c68f960  21:51:12: debug Zone switch changed state! on!

**Comment by cloudsyjared** [comment]
Ok, lights are back.

**Comment by kellydarren** [comment]
Let there be light :-)...cheers jared
