### ISSUE TITLE
Question rather than an Issue

### ISSUE THREAD

**Issue by kellydarren** [cloudsyjared/MiThings#17]
Jared

It seems to happen more when turn off commands are given, rather than turn on commands (even though it does happen for these too)

When I turn on the lights via ST app, the Mi Lights item on the App turns on but the lights haven't.  So I turn them off again via the App and back on again via the APP at which point on the second turn on command the lights actually turn on.

However this happens more regularly, when issuing turn off commands.  It's like a latency or packet loss thing.  Just wondering if you have any insight on why it may be occurring?

Also note it doesn't happen all the time either!!!!

**Comment by cloudsyjared** [comment]
When the turn on happens, any idea what the logs say?

**Comment by kellydarren** [comment]
I haven't checked, primarily as I'm never at a PC when it happens. Next
time, I'll take a look

**Comment by cloudsyjared** [comment]
@kellydarren: here is the new beta endpoint that I just finished work on. I can't make any promises that it will be always available, but if you'd like to temporarily test and see if things are any better, that would help me. 

New endpoint in device cloud settings = cloud.mithings.pw (same port, 38899)
New endpoint in milight manager, smartapp, line 84 =   http://api.mithings.pw/v1/

**Comment by kellydarren** [comment]
Jared

This is the code from ST Live Logging.  The lights on the App are on, your code says they are on, but they didnt come on.

a9a61a99-5cb1-4405-ab36-ea914c68f960  22:21:57: debug Received response: groovyx.net.http.HttpResponseDecorator@343a9a33 on
a9a61a99-5cb1-4405-ab36-ea914c68f960  22:21:57: debug MiLight device: AC:CF:23:53:D3:8E, raw data from cloud: [brightness:29, result:[message:all is well., status:success], hex:#83E3FF, color:32, notify:[message:, title:, hasMessage:0, image:], power:on]
a9a61a99-5cb1-4405-ab36-ea914c68f960  22:21:57: debug MiLight device: AC:CF:23:53:D3:8E, built path: rgbw/power/on/3
a9a61a99-5cb1-4405-ab36-ea914c68f960  22:21:57: debug Zone switch changed state! on!

**Comment by cloudsyjared** [comment]
New endpoint or old?

**Comment by kellydarren** [comment]
Just seeing the new beta endpoints.  I'll hook them up - and let you know.

**Comment by kellydarren** [comment]
Jared, OLD, sorry just amended the comment when I realised you about your new code :-)

**Comment by kellydarren** [comment]
Jared, maybe you can help me.  I upgraded my machine to windows 10 on friday (windows 7 previously).  Using the LimitLessLED app, is not picking up the  hub (even when I hard code the IP).  Using the IP and using a browers I can access the HUB but as far as I can see the Server Name area hasnt been exposed to enter via the web front end.

Any idea how to get the App working with Windows 10. I checked the LimitlessLed site, but not seeing any thing there either.

**Comment by kellydarren** [comment]
Your grand, got it :-), ran the troubleshoot compatibility on the app :-)

**Comment by kellydarren** [comment]
App and Hub Updated

Tried a simple turn lights on - they didn't come on.  Code below 

a9a61a99-5cb1-4405-ab36-ea914c68f960  23:02:10: debug Received response: groovyx.net.http.HttpResponseDecorator@53e02195 on
a9a61a99-5cb1-4405-ab36-ea914c68f960  23:02:10: debug MiLight device: AC:CF:23:53:D3:8E, raw data from cloud: [brightness:100, result:[message:all is well, status:success], hex:#FFFFFF, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
a9a61a99-5cb1-4405-ab36-ea914c68f960  23:02:10: debug MiLight device: AC:CF:23:53:D3:8E, built path: rgbw/power/on/3
a9a61a99-5cb1-4405-ab36-ea914c68f960  23:02:10: debug Zone switch changed state! on!

**Comment by cloudsyjared** [comment]
Well I saw your hub connect to my new servers, but I don't see it trying to connect anymore..

**Comment by cloudsyjared** [comment]
I've found the error in my ways -- give me a little longer to push a fix out to the new endpoint.

**Comment by cloudsyjared** [comment]
Ok, well, at least my little testing, this looks to be able to handle two (or more) of us now :) Let me know how things go?

**Comment by kellydarren** [comment]
Will do....

Were you working on the server over the last 30 mins r so approx. 23.45 to
00.15 GMT

They became unresponsive!!

**Comment by cloudsyjared** [comment]
Yep, the downfalls of using my new endpoint :)

Would have liked to have heard how things were after my changes last 
night...

**Comment by kellydarren** [comment]
That's no problem, I'm well used to dev and test environments :-)

I'm on Greenwich Meantime so when you had your changes done i was well
asleep :-)

I can only test in the late evenings due to other commitments.

I was throwing different instructions at the server last night about 21.30
GMT, colour changes, dimming, on and off and the server responded to them.

I was repeating the exercise again later about 23.45 when you were working
with the code :-)

I did encounter the need to turn the lights on twice before they came on
but that was periodic and not a consistent requirement and you may have
been working on the code or doing a release either at that time.

**Comment by kellydarren** [comment]
Jared
It seems good to me, it has gone down a bit at night, but I've just assumed that is you working on the code.  When its up it seems to be taking instructions well.

**Comment by kellydarren** [comment]
Jared
I got a lone of my brothers hub thought i would run some lights off one server and others off the new one.  However the new hub isnt turning on the any of the lights, but the logging is telling me there have been turned on.

Now when I set it up initially i messed up the mac address and entered one belonging to an existing hub, after working out that mistake I deleted the lights and hub, fixed up the existing lights and re-added back in the new hub.

Is there anything weird showing up in your logs?

**Comment by kellydarren** [comment]
Jared
The new code from what I can see is accepting the commands fine.  On/Off (I still have the issue of having to hit the on or off button 2, whilst in the MiLight App it works the first time) but I'm beginning to wonder might it be the ST hub, due to the fact your code is always showing the On / Off commands.

Is there anything you would like me to throw at it to test a particular aspect?

**Comment by cloudsyjared** [comment]
It may be ST then, I know you gotta give the app some time when you 
first load it as it likes to reset itself when it draws.

The native MiLight app works fine because it can talk UDP directly to 
the hub. Doesn't need SmartThings.


Anyway dude I think I'm going to move on to some different lights. Just 
ordered one of these: 
http://www.aliexpress.com/item/Original-Xiaomi-Mi-Yeelight-LED-Bulb-Colour-Version-Mi-Light-Smartphone-App-WIFI-Control-Light-Eyecare/32662970848.html 
for 20$ shipped. They are wifi bulbs and speak TCP -- can get 
SmartThings working (natively) without a cloud service shim.

FutLight (MiLight manufacturer) wouldn't give me the command codes for 
the new hub without talking to one of their resellers. And since I was 
going to upgrade them all anyway, it may be easier to cut these jokers 
out all together.

**Comment by kellydarren** [comment]
I saw your call out to that guy you were in contact previously - pretty bloody daft by the company not to help when it has the potential of extending their market customers.

I like the @Xiaomi stuff.  There is a thread about their contact sensors which just would not stay joined to ST even though they claimed they are ZWave compatible.  Most people gave up on them in the end.  See links below (BTW I see Xiamoi, just released a robot cleaner today, that would be cool in ST LOL)

https://community.smartthings.com/t/save-your-money-xiaomi-original-series-wont-work-with-smartthings/28610/2

https://community.smartthings.com/t/9-zigbee-xiaomi-door-window-sensors-probably-wont-work-with-smartthings/28607/4

https://community.smartthings.com/t/xiaomi-zigbee-door-window-sensor-motion-sensor-smart-button-device-type-beta/31948/60

**Comment by cloudsyjared** [comment]
I really like this concept:


http://www.aliexpress.com/item/2016-New-Xiaomi-Mi-Cube-Controller-Zigbee-Version-Controlled-by-Six-Actions-with-Phone-App-for/32710921665.html?ws_ab_test=searchweb201556_8,searchweb201602_4_10057_10056_10065_10037_10055_10054_10067_10069_10059_10058_10017_10070_10060_10061_10052_10062_10053_10050_10051,searchweb201603_7&btsid=774d13d0-2d45-4f12-9608-ae3c6f85f966

I think I may order one and see if I can get it working with ST. 16$ 
shipped, it's a cube (flipable) and spinable, so for instance I could 
flip it to side 2, and spin 180 (imagine a knob) and turn the lights down.

Cool or what?

**Comment by kellydarren** [comment]
I saw that the other night - all good until your drunk and you can not remember what one you have tried already :-)

I dont know where your based but if in Europe theres a site called banggood (brilliant name :-) ) and they are doing sales at the moment.  One of the shops is Xiaomi, you might found a deal there http://www.banggood.com/brands-xiaomi-b-56.html?bid=13953

**Comment by LimitlessLED** [comment]
They don't actually have the commands for the new RGBWW/CW bulbs, that’s why they can't give them, they just didn't want to look silly, so they just made up some excuse, they also probably thought you were asking for RGBW v5 commands.  The v5 hub is hardcoded inside the microcontroller mcu to only the codes listed on my website under www.limitlessled.com/dev   When the new hub is designed, which it isn't, then the new commands will be available, it's not that they don't want to give them to you. it is totally not true. Cheers, Hamish.

**Comment by cloudsyjared** [comment]
@LimitlessLED thanks for the heads up. I was hoping to get a head start on v6.
