### ISSUE TITLE
No Light Control

### ISSUE THREAD

**Issue by hotdun** [cloudsyjared/MiThings#19]
Your system was working last week but as of now, I'm not able to control the lights.  The light labels in ST are changing On/Off appropriately.  See below for my Live Logging and thanks in advance!

20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:59 AM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:off]
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:59 AM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/off/1
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:59 AM: debug Zone switch changed state! off!
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:51 AM: debug Received response: groovyx.net.http.HttpResponseDecorator@de858c3 off
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:51 AM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:off]
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:51 AM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/off/2
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:51 AM: debug Zone switch changed state! off!
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:43 AM: debug Zone switch changed state! on!
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:42 AM: debug getChildDevices(false), children=5
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:42 AM: debug Received response: groovyx.net.http.HttpResponseDecorator@58af0448 on
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:42 AM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:42 AM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/on/0
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:42 AM: debug master switch on! AC:CF:23:C3:A0:CA / MiLight Master
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:43 AM: debug Zone switch changed state! on!
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:43 AM: debug Zone switch changed state! on!
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:43 AM: debug Zone switch changed state! on!
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:27 AM: debug Zone switch changed state! off!
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:27 AM: debug getChildDevices(false), children=5
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:27 AM: debug Received response: groovyx.net.http.HttpResponseDecorator@5bcd8aaa off
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:27 AM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:off]
20459962-5918-41b2-8b39-dddb9ff5d0cc  11:12:27 AM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/off/0
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:27 AM: debug master switch off! AC:CF:23:C3:A0:CA / MiLight Master
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:27 AM: debug Zone switch changed state! off!
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:27 AM: debug Zone switch changed state! off!
eb39906a-30df-4dcd-87ae-8f7ab253db66  11:12:27 AM: debug Zone switch changed state! off!

**Comment by cloudsyjared** [comment]
Let me know if it's working now?

**Comment by hotdun** [comment]
Still nothing, thanks for checking into it.  Here are some new logs:

eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:55 PM: debug Zone switch changed state! on!
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:55 PM: debug getChildDevices(false), children=5
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:55 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@57bf718a on
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:55 PM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:55 PM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/on/0
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:55 PM: debug master switch on! AC:CF:23:C3:A0:CA / MiLight Master
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:52 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@351d6b8d on
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:52 PM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:52 PM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/on/1
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:51 PM: debug Zone switch changed state! on!
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:49 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@272ef63d on
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:49 PM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:49 PM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/on/2
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:49 PM: debug Zone switch changed state! on!
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:46 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@2eab0242 on
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:46 PM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:46 PM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/on/3
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:46 PM: debug Zone switch changed state! on!
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:28 PM: debug Zone switch changed state! off!
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:28 PM: debug Zone switch changed state! off!
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:28 PM: debug getChildDevices(false), children=5
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:28 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@7c48f977 off
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:28 PM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:off]
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:28 PM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/off/0
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:28 PM: debug master switch off! AC:CF:23:C3:A0:CA / MiLight Master
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:28 PM: debug Zone switch changed state! off!
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:28 PM: debug Zone switch changed state! off!
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:24 PM: debug getChildDevices(false), children=5
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:24 PM: debug Received response: groovyx.net.http.HttpResponseDecorator@101e4863 on
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:24 PM: debug MiLight device: AC:CF:23:C3:A0:CA, raw data from cloud: [brightness:100, result:[message:all is well., status:success], hex:#FDF8EC, color:0, notify:[message:, title:, hasMessage:0, image:], power:on]
20459962-5918-41b2-8b39-dddb9ff5d0cc  4:07:24 PM: debug MiLight device: AC:CF:23:C3:A0:CA, built path: rgbw/power/on/0
eb39906a-30df-4dcd-87ae-8f7ab253db66  4:07:24 PM: debug master switch on! AC:CF:23:C3:A0:CA / MiLight Master

**Comment by cloudsyjared** [comment]
Try restarting the hub

**Comment by hotdun** [comment]
That was it!  All working now.  Any idea what happened?
